version: "3.8"
services: 
  react-project:
    build: ./project_react_app
    ports: 
      - "3000:80"
    depends_on:
      - express-project
      
  express-project:
    build: ./project_express_app
    ports:
      - "3001:3001"

